/**
 * Message domain model
 *
 * Represents a single message within a conversation.
 * Can be from the user (inbound) or from the bot (outbound).
 */

import { WhatsappMessageType } from './WhatsappWebhook';

/**
 * Message direction
 */
export enum MessageDirection {
  /** Message from user to bot */
  INBOUND = 'inbound',

  /** Message from bot to user */
  OUTBOUND = 'outbound',
}

/**
 * Message sender type
 */
export enum MessageSender {
  /** Message sent by the user */
  USER = 'user',

  /** Message sent by the bot (AI) */
  BOT = 'bot',

  /** Message sent by a human agent */
  HUMAN = 'human',

  /** System message (automated) */
  SYSTEM = 'system',
}

/**
 * Message status (for outbound messages)
 */
export enum MessageStatus {
  /** Message is being sent */
  SENDING = 'sending',

  /** Message successfully sent to WhatsApp */
  SENT = 'sent',

  /** Message delivered to user's device */
  DELIVERED = 'delivered',

  /** Message read by user */
  READ = 'read',

  /** Message failed to send */
  FAILED = 'failed',
}

/**
 * Basic message content
 *
 * @description
 * Stores the actual content of the message.
 * Structure varies based on message type.
 */
export interface MessageContent {
  /** Text content (for text messages) */
  text?: {
    body: string;
  };

  /** Image content (for image messages) */
  image?: {
    id?: string;
    link?: string;
    key?: string;
    mime_type?: string;
    sha256?: string;
    caption?: string;
  };

  /** Video content (for video messages) */
  video?: {
    id: string;
    mime_type: string;
    sha256: string;
    caption?: string;
  };

  /** Audio content (for audio/voice messages) */
  audio?: {
    id: string;
    mime_type: string;
    sha256: string;
    voice?: boolean;
  };

  /** Document content (for document messages) */
  document?: {
    id: string;
    filename: string;
    mime_type: string;
    sha256: string;
    caption?: string;
  };

  /** Sticker content (for sticker messages) */
  sticker?: {
    id: string;
    mime_type: string;
    sha256: string;
    animated: boolean;
  };

  /** Interactive content (for button/list messages) */
  interactive?: {
    type: 'list' | 'button';
    body: {
      text: string;
    };
    header?: {
      type: 'text';
      text: string;
    };
    footer?: {
      text: string;
    };
    action?: unknown; // Flexible for different interactive types
  };

  // 🔮 Future fields:
  // location?: unknown;     // For location messages
}

/**
 * AI metadata for bot-generated messages
 *
 * @description
 * Tracks AI model usage and generation details for bot responses.
 */
export interface MessageAIMetadata {
  /** Whether this message was generated by AI */
  isAiGenerated: boolean;

  /** AI model used (e.g., gpt-4o-mini) */
  model?: string;

  /** Tokens used in generation */
  tokensUsed?: {
    prompt: number;
    completion: number;
    total: number;
  };

  /** Response generation time in milliseconds */
  responseTime?: number;

  /** Model temperature used */
  temperature?: number;

  /** Prompt version identifier */
  promptVersion?: string;

  // 🔮 Future fields:
  // usedTools?: Array<{ toolName: string; executionTime: number }>;
  // ragContexts?: Array<{ contextId: string; relevanceScore: number }>;
  // confidence?: number;
}

/**
 * Error information for failed messages
 */
export interface MessageError {
  /** Error code */
  code: string;

  /** Error message */
  message: string;

  /** When the error occurred */
  timestamp: Date;
}

/**
 * Context information for reply messages
 */
export interface MessageContext {
  /** WhatsApp message ID that this message is replying to */
  messageId: string;

  /** Phone number that sent the original message */
  from: string;

  /** Complete message object that this message is replying to */
  repliedMessage?: Message;
}

/**
 * Interactive message types
 */
export enum InteractiveMessageType {
  /** User selected an option from a list */
  LIST_REPLY = 'list_reply',

  /** User clicked a button */
  BUTTON_REPLY = 'button_reply',
}

/**
 * Interactive message details
 */
export interface InteractiveDetails {
  /** Type of interactive message */
  type: InteractiveMessageType;

  /** Selected item details */
  selectedItem: {
    /** ID of the selected item */
    id: string;

    /** Title of the selected item */
    title: string;

    /** Description of the selected item */
    description?: string;
  };
}

/**
 * Main message interface
 *
 * @description
 * Represents a single message in a conversation.
 * Contains the message content, metadata, and tracking information.
 */
export interface Message {
  /** WhatsApp message ID (from WhatsApp API) - For inbound messages */
  messageId: string;

  /**
   * WhatsApp Message ID (wamid) returned by Meta when we send a message
   *
   * @description
   * This is the unique identifier that WhatsApp assigns to our outbound messages.
   * Used to track delivery status via status webhooks.
   * Only populated for OUTBOUND messages.
   *
   * Format: wamid.HBgMNTczMTEzMjMwMDMzFQIAERgSRkZCQ0U0ODYzMjBGMjA5QjRFAA==
   *
   * @example "wamid.HBgMNTczMTEzMjMwMDMzFQIAERgSRkZCQ0U0ODYzMjBGMjA5QjRFAA=="
   */
  whatsappMessageId?: string;

  /** Conversation this message belongs to */
  conversationId: string;

  /** Message direction (inbound/outbound) */
  direction: MessageDirection;

  /** Who sent this message */
  sender: MessageSender;

  /** Message type (from WhatsApp) */
  type: WhatsappMessageType;

  /** Message content */
  content: MessageContent;

  /**
   * Message delivery status (for outbound messages)
   *
   * @description
   * Tracks the delivery lifecycle of bot messages:
   * - SENDING: Initial state when saving to DB
   * - SENT: WhatsApp confirmed receipt
   * - DELIVERED: Message reached user's device
   * - READ: User opened the message
   * - FAILED: Message failed to send
   *
   * Updated via status webhooks from WhatsApp.
   */
  status?: MessageStatus;

  /** AI metadata (for bot messages) */
  aiMetadata?: MessageAIMetadata;

  /** Error information (if message failed) */
  error?: MessageError;

  /** When the message was created/sent */
  timestamp: Date;

  /** When the message was marked as read (for inbound) */
  readAt?: Date;

  /** Context information for reply messages */
  context?: MessageContext;

  /** Interactive message details (for user selections) */
  interactiveDetails?: InteractiveDetails;
}

/**
 * DTO for creating a new message
 */
export interface CreateMessageDTO {
  messageId: string;
  conversationId: string;
  direction: MessageDirection;
  sender: MessageSender;
  type: WhatsappMessageType;
  content: MessageContent;
  timestamp: Date;
  context?: MessageContext;
  interactiveDetails?: InteractiveDetails;
}

/**
 * DTO for creating a bot message
 */
export interface CreateBotMessageDTO {
  conversationId: string;
  content: MessageContent;
  aiMetadata: MessageAIMetadata;
}

/**
 * Message history item for AI context
 *
 * @description
 * Simplified message format for passing to AI model.
 * Contains only essential information for context.
 */
export interface MessageHistoryItem {
  /** Who sent the message */
  role: 'user' | 'assistant' | 'system';

  /** Message text content */
  content: string;

  /** Message timestamp */
  timestamp: Date;

  /** Message type (for reference) */
  type?: WhatsappMessageType;
}
