name: Detect Path Changes
description: Determine whether predefined path filters were modified in the current workflow run.

inputs:
  filters:
    description: YAML definition of the path filters to evaluate.
    required: true

outputs:
  changes:
    description: JSON array containing names of all filters matching any of changed files
    value: ${{ steps.filter.outputs.changes }}

runs:
  using: composite
  steps:
    - name: Evaluate path filters
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: ${{ inputs.filters }}
