name: Detect Path Changes
description: Determine whether predefined path filters were modified in the current workflow run.

inputs:
  filters:
    description: YAML definition of the path filters to evaluate.
    required: true

outputs:
  filters-json:
    description: JSON object containing the evaluation result for each configured filter.
    value: ${{ steps.filter.outputs.json }}

runs:
  using: composite
  steps:
    - name: Evaluate path filters
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: ${{ inputs.filters }}
